### ISSUE TITLE
Add about/team link with link to profiles

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-automation.github.io#30]

**Comment by ogenstad** [comment]
Any thoughts about which url to use /team/ ?

Then perhaps /about/ could be something about the project itself?

**Comment by dbarrosop** [comment]
I think we can have it in the /about endpoint for now. If we fill it with something else in the future we can have inside /about a link to "meet the team" or something. We don't want to bloat the categories right at the beginning :P

**Comment by ogenstad** [comment]
I've created a few PRs which can be tested locally. All of these will probably need to be rebased after adding more info and images. Example 2 looks a bit strange with the different size images. But the same design is used at the bottom of Example 3 so you can see what it would look like with correctly sized images. The upper part of Example 1 and 3 should also have images which are about the same dimensions.

But pull them and view the /about/ page locally, let me know what you think and prefer.

**Comment by dbarrosop** [comment]
I think I prefer example 2. The others two look a bit intimidating, too grandiose :P

**Comment by ogenstad** [comment]
Think big. ;)

I'll rebase that one after #28 and #29 are solved. You guys can also consider if we should use the bio variable from _site/authors.yml which will also be shown in the sidebar if that author writes a blog post or if we should create a new variable for the text in the /about/ page. Also if it should be square or rectangular pictures..

**Comment by ogenstad** [comment]
Closed with #35.
